# Generated by Django 4.1.2 on 2022-12-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('company_name', models.CharField(max_length=50)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField(null=True)),
            ],
        ),
    ]
