# Generated by Django 2.2.16 on 2021-03-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('summary', models.CharField(max_length=400)),
                ('start_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
