# Generated by Django 2.2.16 on 2021-02-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200916_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='descript',
            field=models.TextField(),
        ),
    ]
