"""
Django settings for portfolio project.
Generated by 'django-admin startproject' using Django 3.0.8.
For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'a9av0via0@c4od7!kd+vfimj#^c4_42a5tu@&kk3_&ex_xvn*t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'blog.apps.BlogConfig',
    'jobs.apps.JobsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ckeditor',
    'django_social_share',
    'accounts',
    'mptt'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'portfolio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['portfolio/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

TEMPLATE_DIR = os.path.join(BASE_DIR, 'templates')

WSGI_APPLICATION = 'portfolio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'portfoliodb',
        'USER': 'postgres',
        'PASSWORD': 'django1234',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Baku'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'portfolio/static')
]
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

CKEDITOR_JQUERY_URL = '//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'
CKEDITOR_BASEPATH = "/static/ckeditor/ckeditor/"
CKEDITOR_CONFIGS = {
         # django-ckeditor uses the default configuration by default
    'default': {
                 # Editor width adaptive
        'width':'auto',
        'height':'250px',
                 # Tab key to convert the number of spaces
        'tabSpaces': 4,
                 # Toolbar style
        'toolbar': 'Custom',
                 # Toolbar button
        'toolbar_Custom': [
                         # Emoji code block
            ['Smiley', 'CodeSnippet'],
            ['Format'],
                         # Font style
            ['Bold', 'Italic', 'Underline', 'RemoveFormat', 'Blockquote'],
                         # font color 
            ['TextColor', 'BGColor'],
                         # Link
            ['Link', 'Unlink'],
                         # List
            ['NumberedList', 'BulletedList'],
                         # Maximize
            ['Maximize'],
            ['Source'],
            ['Table', 'Tabletools'],
            ['Image']
        ],
        # Add code block plugin
        'codeSnippet_languages': {
            'python': 'Python <3',
            'c': 'C',
            'cpp': 'C++',
            'csharp': 'C#',
            'bash': 'Bash',
            'aspnet': 'ASP.NET',
            'dart': 'Dart',
            'docker': 'Docker',
            'flutter': 'Flutter',
            'fortran': 'Fortran',
            'haskel': 'Haskel',
            'markup': 'HTML',
            'http': 'HTTP',
            'git': 'Git',
            'go': 'Golang',
            'java': 'Java',
            'javascript': 'JavaScript',
            'makefile':'Makefile',
            'matlab': 'MATLAB',
            'nginx': 'Nginx',
            'pascal': 'Pascal',
            'perl': "Perl",
            'php': 'PHP',
            'rust': 'Rust',
            'ruby': 'Ruby',
            'r': 'R',
            'sas': 'SAS',
            'scala': 'Scala',
            'scheme': 'Scheme',
            'sql': 'SQL',
            'swift': 'Swift',
            'vim': 'Vim',
            'yml': 'YML'
        },
       
        'extraPlugins': ','.join(['codesnippet', 'prism', 'widget', 'lineutils', 'table', 'clipboard', 'format',
                                  'image', 'tabletools']),

    }
}

try:
    from .local_settings import *
except ImportError:
    pass