name: Django CI

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - name: fix permissions
      run: |
        cd ~/deployPortfolio
        sudo chown -R $USER:$USER *
        cd _work/portfolio-project/portfolio-project
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        clean: false
    - name: Configure and Run
      run: |
        cp ~/portfolio-project/.env ./.env
        docker-compose up -d --build
