name: Django CI

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - name: Change Permission
    - run: sudo chown -R $USER:$USER /home/hackU/deployPortfolio/_work/{portfolio-project}
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Configure and Run
      run: |
        mv ~/portfolio-project/.env ./.env
        docker-compose up -d --build
