name: Django CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Run Server
      run: |
        echo "Current working dir:"
        pwd
        docker-compose up -d --build
